//go:build !ignore_autogenerated

// Code generated by hand to mirror controller-gen output; keep in sync with
// resourcepolicy_types.go. DeepCopy* methods satisfy runtime.Object.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies the receiver into out.
func (in *ContainerExclusion) DeepCopyInto(out *ContainerExclusion) {
	*out = *in
}

// DeepCopy returns a deep copy of ContainerExclusion.
func (in *ContainerExclusion) DeepCopy() *ContainerExclusion {
	if in == nil {
		return nil
	}
	out := new(ContainerExclusion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *GitOpsTarget) DeepCopyInto(out *GitOpsTarget) {
	*out = *in
	if in.PRLabels != nil {
		l := make([]string, len(in.PRLabels))
		copy(l, in.PRLabels)
		out.PRLabels = l
	}
}

// DeepCopy returns a deep copy of GitOpsTarget.
func (in *GitOpsTarget) DeepCopy() *GitOpsTarget {
	if in == nil {
		return nil
	}
	out := new(GitOpsTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *ResourceThresholds) DeepCopyInto(out *ResourceThresholds) {
	*out = *in
}

// DeepCopy returns a deep copy of ResourceThresholds.
func (in *ResourceThresholds) DeepCopy() *ResourceThresholds {
	if in == nil {
		return nil
	}
	out := new(ResourceThresholds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *ContainerRecommendation) DeepCopyInto(out *ContainerRecommendation) {
	*out = *in
}

// DeepCopy returns a deep copy of ContainerRecommendation.
func (in *ContainerRecommendation) DeepCopy() *ContainerRecommendation {
	if in == nil {
		return nil
	}
	out := new(ContainerRecommendation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *ResourcePolicySpec) DeepCopyInto(out *ResourcePolicySpec) {
	*out = *in
	if in.NamespaceSelector != nil {
		out.NamespaceSelector = in.NamespaceSelector.DeepCopy()
	}
	if in.WorkloadSelector != nil {
		out.WorkloadSelector = in.WorkloadSelector.DeepCopy()
	}
	out.CPU = in.CPU
	out.Memory = in.Memory
	if in.Exclusions != nil {
		l := make([]ContainerExclusion, len(in.Exclusions))
		copy(l, in.Exclusions)
		out.Exclusions = l
	}
	if in.GitOps != nil {
		out.GitOps = in.GitOps.DeepCopy()
	}
}

// DeepCopy returns a deep copy of ResourcePolicySpec.
func (in *ResourcePolicySpec) DeepCopy() *ResourcePolicySpec {
	if in == nil {
		return nil
	}
	out := new(ResourcePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *ResourcePolicyStatus) DeepCopyInto(out *ResourcePolicyStatus) {
	*out = *in
	if in.LastReconcileTime != nil {
		out.LastReconcileTime = in.LastReconcileTime.DeepCopy()
	}
	if in.Recommendations != nil {
		l := make([]ContainerRecommendation, len(in.Recommendations))
		copy(l, in.Recommendations)
		out.Recommendations = l
	}
	if in.Conditions != nil {
		l := make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&l[i])
		}
		out.Conditions = l
	}
}

// DeepCopy returns a deep copy of ResourcePolicyStatus.
func (in *ResourcePolicyStatus) DeepCopy() *ResourcePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ResourcePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *ResourcePolicy) DeepCopyInto(out *ResourcePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of ResourcePolicy.
func (in *ResourcePolicy) DeepCopy() *ResourcePolicy {
	if in == nil {
		return nil
	}
	out := new(ResourcePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject satisfies runtime.Object.
func (in *ResourcePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *ResourcePolicyList) DeepCopyInto(out *ResourcePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]ResourcePolicy, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

// DeepCopy returns a deep copy of ResourcePolicyList.
func (in *ResourcePolicyList) DeepCopy() *ResourcePolicyList {
	if in == nil {
		return nil
	}
	out := new(ResourcePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject satisfies runtime.Object.
func (in *ResourcePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
